# Generated by Django 3.0.5 on 2020-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0002_auto_20200420_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerroadmaptask',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='trackerroadmaptask',
            unique_together={('position', 'tracker_roadmap')},
        ),
    ]
