# Generated by Django 3.0.5 on 2020-04-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0003_auto_20200422_1117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackerroadmaptask',
            unique_together={('task', 'tracker_roadmap')},
        ),
    ]
